### ISSUE TITLE
#1 Epic: User Authentication

### ISSUE THREAD

**Issue by Alisha98A** [Alisha98A/lumiere-dining#5]
This epic includes the following User Stories:

- [ ] #2 User Story: Create an account
- [ ] #3 User Story: Log in to account
- [ ] #4 User Story: Reset password
